### ISSUE TITLE
First radio button doesn't get focus-ring

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-control-state-mixin#25]
Affected browsers: Firefox and most probably all polyfilled browsers

Live demo: https://limonte.github.io/csm-issue/index.html

When I tabbing the first radio buttons doesn't get focus-ring:

![recorded](https://user-images.githubusercontent.com/6059356/30736264-b710e436-9f8a-11e7-90e3-8c65390083b4.gif)

**Comment by tomivirkki** [comment]
The live demo doesn't work for me on Firefox

**Comment by limonte** [comment]
> The live demo doesn't work for me on Firefox

Hm, tested in Linux/Firefox and Win/Firefox and it works fine.

**Comment by jouni** [comment]
@limonte, can you test if this is still valid with the latest version: https://cdn.vaadin.com/vaadin-radio-button/1.0.0-alpha12/demo/#radio-group-demos

**Comment by tomivirkki** [comment]
Seems to be working fine with the latest version. Closing.
