### ISSUE TITLE
Deprecate `focused` property

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-control-state-mixin#26]
The focused state should not end up in public API.

Instead `(document || shadowRoot).activeElement` standard DOM API should be used to find focused element. Focus change notification triggers standard focus events.

Include https://github.com/vaadin/vaadin-control-state-mixin/issues/23

**Comment by jouni** [comment]
Does this mean that the `[focused]` state attribute is also removed? I suppose we need to rely on the `:focus` pseudo-class instead then, right?

**Comment by platosha** [comment]
Nope. The attribute should be kept for styling purposes.

`:focus` pseudo-class is unreliable for host styling. Obviously, it wouldn’t match the host when the actual focused element is in shadow DOM.

**Comment by jouni** [comment]
Ah, of course – I didn’t actually think about this too much :D
