### ISSUE TITLE
Fix dev dependencies

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-control-state-mixin#30]
The element shouldn't depend on `master` versions in devDependencies.

- Create `1.x` branch and fix the devDependencies to use pre-valo-marge versions there (remove radio-button dependency altogether). release patch version 1.X.

- For the current master, depend on new genration Valo versions. release patch version 2.X.

**Comment by yuriy-fix** [comment]
https://github.com/vaadin/vaadin-control-state-mixin/releases/tag/v1.1.9

https://github.com/vaadin/vaadin-control-state-mixin/releases/tag/v2.0.1
