### ISSUE TITLE
Support elements without shadowRoot

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-control-state-mixin#51]
It would be useful to be able to get the behaviour provided by this mixin even in any focusable custom elements which don't have a `shadowRoot`, or which [stamp a template into light DOM](https://polymer-library.polymer-project.org/2.0/docs/devguide/dom-template#stamp-templates-in-light-dom).

Currently in `ready()` the mixin does:
```js
this.shadowRoot.addEventListener('focusin', ensureEventComposed);
this.shadowRoot.addEventListener('focusout', ensureEventComposed);
```

This fails if the element has no shadow DOM and thus no `shadowRoot` property.

This part could be fixed by an approach like this:
```js
const root = this.shadowRoot || this;
root.addEventListener('focusin', ensureEventComposed);
root.addEventListener('focusout', ensureEventComposed);
```

But I'm not sure if something additional needs to be done to make it work for custom elements without a shadow root.

**Comment by web-padawan** [comment]
That code is actually a workaround for specific Firefox version (61-62 or so). Ideally, we should remove it and avoid adding such listeners for other browsers, or have a fix like what you suggested 👍

**Comment by web-padawan** [comment]
I don't think we have any plans related to supporting components without a shadow root. 
IMO attempting to do it would result in over-engineering.

It would make more sense to instead try `delegatesFocus` which is already supported in Chrome and Safari TP. So let me close this issue in favor of https://github.com/vaadin/component-mixins/issues/8
