### ISSUE TITLE
Unify focus-ring behavior across components

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-control-state-mixin#56]
Currently, there is an inconsistency:

1.  Components depending on `vaadin-list-mixin` (ListBox & Tabs) set `focus-ring` **unless** there was mousedown event (see [code](https://github.com/vaadin/vaadin-item/blob/4d361148606871f43a42c46343ed5529cb78d78e/src/vaadin-item-mixin.html#L118-L120))

2. Components depending on `vaadin-control-state-mixin` (Button, TextField etc) do NOT set `focus-ring` **unless** <kbd>Tab</kbd> was pressed:
https://github.com/vaadin/vaadin-control-state-mixin/blob/df6c6718e8f673b9d47952dcc377e5f631774708/vaadin-control-state-mixin.html#L193-L195

IMO, the latter should be changed so that behavior is consistent and align with option 1. 

The way to handle it would be to listen for top-level keydown and mousedown events.
This is already done for [LitElement version](https://github.com/vaadin/component-mixins/blob/a7487fbfc7036e78039040eb11ec65b4df62816d/packages/focus-visible-mixin/focus-visible-mixin.ts#L79-L81).

**Comment by web-padawan** [comment]
Note: it makes sense to also introduce an internal option to force `focus-ring` to cover #50.

**Comment by alump** [comment]
What I tested, as now all events (except mouse) will cause focus ring, the #50 is also covered by this.

**Comment by knoobie** [comment]
@web-padawan I'm wondering, if this could be seen as improvement, before you have to reinvent the wheel again. I think this could really help in the long run. https://github.com/twbs/bootstrap/pull/30872

**Comment by web-padawan** [comment]
@knoobie thanks, I'm aware of this polyfill, and I think it is worth trying. Not sure if we want to do it in minor release though.

**Comment by knoobie** [comment]
@web-padawan You are right! It sounds more like something for next gen (lit-elements).
